package be.notification.event;

public enum GreenroomNotificationEventType {
	GREENROOM_TICKET_CREATED,
	GREENROOM_TICKET_RESOLVED,
	GREENROOM_TICKET_DELETED,
	GREENROOM_USER_NOTIFICATION_PREFERENCE_UPDATED
}
