package be.greenroom.tracking.domain;

public enum ResolvedHelpType {
	SIMILAR_STORY_EMPATHY,
	RECOMMENDED_ACTION_WORKED,
	COMMUNICATION_RESOLVED,
	TIME_NATURALLY_RESOLVED,
	CONSULTED_ACQUAINTANCE,
	ETC
}
