package be.greenroom.tracking.domain;

public enum UnresolvedNeedType {
	CALM_EMOTION_FIRST,
	ORGANIZE_SITUATION_LOGICALLY,
	NEED_SMALL_ACTION,
	NEED_OTHERS_ADVICE,
	NEED_PSYCHOLOGICAL_STABILITY,
	ETC
}
